sensors:
  - id: 0
    name: "hokuyo-a"
    transport: "tcp"
    endpoint: "192.168.1.10:10940"
    pose: { tx: 0.0, ty: 0.0, theta: 0.0 }
    enabled: true
    mask:
      angle: { min: -2.356, max: 2.356 }
      range: { near: 0.05,  far: 15.0 }
  - id: 1
    name: "hokuyo-b"
    transport: "tcp"
    endpoint: "192.168.1.11:10940"
    pose: { tx: 2.4, ty: 0.3, theta: 1.57 }
    enabled: true
    mask:
      angle: { min: -1.57, max: 1.57 }
      range: { near: 0.10,  far: 10.0 }

world_mask:
  polygon: []   # [[x,y], ...]

dbscan:
  eps: 0.12
  minPts: 6

sinks:
  - { type: "nng", url: "tcp://0.0.0.0:5555", topic: "clusters", encoding: "msgpack", rate_limit: 120 }

ui:
  ws_listen: "0.0.0.0:8080"
  rest_listen: "0.0.0.0:8080"