sensors:
  - id: 0
    name: "hokuyo-a"
    type: "hokuyo_urg_eth"
    endpoint: "192.168.104.202:10940"
    pose: { tx: 0.0, ty: 0.0, theta: 0.0 }
    enabled: true
    mode: "ME"          # "MD"=距離のみ / "ME"=距離+強度
    skip_step: 0          # 0ならダウンサンプリング無し
    interval: 0         # 0=既定（ms）
    mask:
      angle: { min: -135.0, max: 135.0 }  # degree
      range: { near: 0.05, far: 15.0 }    # m

world_mask:
  polygon: []   # [[x,y], ...]

dbscan:
  eps_norm: 5       # Normalized distance threshold
  minPts: 5           # Minimum points for core (inclusive of self)
  k_scale: 1        # Angular term scale coefficient (1.0 = theoretical optimum)
  
  # Performance parameters
  h_min: 0.01         # Minimum grid cell size [m]
  h_max: 0.20         # Maximum grid cell size [m]
  R_max: 5            # Maximum search radius in cells
  M_max: 600          # Maximum candidate points per query

prefilter:
  enabled: true
  
  neighborhood:
    enabled: true
    k: 5                    # Minimum neighbors required
    r_base: 0.05            # Base radius [m]
    r_scale: 1.0            # Distance-based radius scaling factor
  
  spike_removal:
    enabled: true
    dr_threshold: 0.3       # |dR/dθ| threshold for spike detection
    window_size: 3          # Window size for derivative calculation
  
  outlier_removal:
    enabled: true
    median_window: 5        # Window size for moving median
    outlier_threshold: 2.0  # Threshold in standard deviations
    use_robust_regression: false
  
  intensity_filter:
    enabled: false          # Disabled by default (sensor dependent)
    min_intensity: 0.0      # Minimum intensity threshold
    min_reliability: 0.0    # Minimum reliability threshold
  
  isolation_removal:
    enabled: true
    min_cluster_size: 3     # Minimum points to keep a cluster
    isolation_radius: 0.1   # Radius to check for isolation

postfilter:
  enabled: true
  
  isolation_removal:
    enabled: true
    min_points_size: 3     # Minimum points to keep a cluster
    isolation_radius: 0.2   # Radius to check for isolation between clusters
    required_neighbors: 2   # Minimum neighbors required for a point to be considered part of a cluster

sinks:
  - { type: "nng", url: "tcp://0.0.0.0:5555", topic: "clusters", encoding: "msgpack", rate_limit: 120 }

ui:
  ws_listen: "0.0.0.0:8080"
  rest_listen: "0.0.0.0:8080"