sensors:
  - id: 0
    name: "hokuyo-a"
    type: "hokuyo_urg_eth"
    endpoint: "192.168.104.202:10940"
    pose: { tx: 0.0, ty: 0.0, theta: 0.0 }
    enabled: true
    mode: "ME"          # "MD"=距離のみ / "ME"=距離+強度
    skip_step: 0          # 0ならダウンサンプリング無し
    interval: 0         # 0=既定（ms）
    mask:
      angle: { min: -135.0, max: 135.0 }  # degree
      range: { near: 0.05, far: 15.0 }    # m

world_mask:
  polygon: []   # [[x,y], ...]

dbscan:
  eps_norm: 5       # Normalized distance threshold
  minPts: 5           # Minimum points for core (inclusive of self)
  k_scale: 1        # Angular term scale coefficient (1.0 = theoretical optimum)
  
  # Performance parameters
  h_min: 0.01         # Minimum grid cell size [m]
  h_max: 0.20         # Maximum grid cell size [m]
  R_max: 5            # Maximum search radius in cells
  M_max: 600          # Maximum candidate points per query

sinks:
  - { type: "nng", url: "tcp://0.0.0.0:5555", topic: "clusters", encoding: "msgpack", rate_limit: 120 }

ui:
  ws_listen: "0.0.0.0:8100"
  rest_listen: "0.0.0.0:8100"