sensors:
  - id: 0
    name: "hokuyo-a"
    type: "hokuyo_urg_eth"
    endpoint: "192.168.104.202:10940"
    pose: { tx: 0.0, ty: 0.0, theta: 0.0 }
    enabled: true
    mode: "ME"          # "MD"=距離のみ / "ME"=距離+強度
    skip_step: 0          # 0ならダウンサンプリング無し
    interval: 0         # 0=既定（ms）
    mask:
      angle: { min: -135.0, max: 135.0 }  # degree
      range: { near: 0.05, far: 15.0 }    # m

world_mask:
  polygon: []   # [[x,y], ...]

dbscan:
  eps: 0.12
  minPts: 6

sinks:
  - { type: "nng", url: "tcp://0.0.0.0:5555", topic: "clusters", encoding: "msgpack", rate_limit: 120 }

ui:
  ws_listen: "0.0.0.0:8080"
  rest_listen: "0.0.0.0:8080"