sensors:
  - id: "test_sensor"
    type: "hokuyo_urg_eth"
    name: "Test Sensor"
    endpoint: "192.168.1.10:10940"
    enabled: true
    mode: "ME"
    interval: 0
    skip_step: 1
    ignore_checkSumError: 1
    pose:
      tx: 0.0
      ty: 0.0
      theta: 0.0
    mask:
      angle:
        min: -180.0
        max: 180.0
      range:
        near: 0.05
        far: 15.0

dbscan:
  eps_norm: 2.5
  minPts: 5
  k_scale: 1.0
  h_min: 0.01
  h_max: 0.20
  R_max: 5
  M_max: 600

prefilter:
  enabled: true
  neighborhood:
    enabled: true
    k: 5
    r_base: 0.05
    r_scale: 1.0
  spike_removal:
    enabled: true
    dr_threshold: 0.3
    window_size: 3
  outlier_removal:
    enabled: true
    median_window: 5
    outlier_threshold: 2.0
    use_robust_regression: false
  intensity_filter:
    enabled: false
    min_intensity: 0.0
    min_reliability: 0.0
  isolation_removal:
    enabled: true
    min_cluster_size: 3
    isolation_radius: 0.1

postfilter:
  enabled: true
  isolation_removal:
    enabled: true
    min_points_size: 3
    isolation_radius: 0.1
    required_neighbors: 2

ui:
  listen: "0.0.0.0:8080"

security:
  api_token: ""

world_mask:
  include: []
  exclude: []

sinks:
  - type: "nng"
    url: "tcp://0.0.0.0:5555"
    encoding: "msgpack"
    topic: "clusters"
    rate_limit: 30
  - type: "nng"
    url: "tcp://0.0.0.0:5556"
    encoding: "json"
    topic: "lidar_data"
    rate_limit: 60
  - type: "osc"
    url: "osc://127.0.0.1:7000/hokuyohub/cluster"
    in_bundle: false
    bundle_fragment_size: 0
    topic: "clusters"
    rate_limit: 20
  - type: "osc"
    url: "osc://127.0.0.1:7001/hokuyohub/data"
    in_bundle: true
    bundle_fragment_size: 1200
    topic: "sensor_data"
    rate_limit: 40