# Helper script to check if a file exists for URG library build verification
# Usage: cmake -DFILE_TO_CHECK=<file_path> -P cmake/check_file_exists.cmake

if(NOT DEFINED FILE_TO_CHECK)
    message(FATAL_ERROR "FILE_TO_CHECK must be defined")
endif()

if(EXISTS ${FILE_TO_CHECK})
    if(IS_DIRECTORY ${FILE_TO_CHECK})
        message(STATUS "✓ Path exists but is a directory: ${FILE_TO_CHECK}")
    else()
        file(SIZE ${FILE_TO_CHECK} FILE_SIZE)
        message(STATUS "✓ File exists: ${FILE_TO_CHECK} (${FILE_SIZE} bytes)")
    endif()
else()
    message(STATUS "✗ File does not exist: ${FILE_TO_CHECK}")
    # For debugging, also check if parent directory exists
    get_filename_component(PARENT_DIR ${FILE_TO_CHECK} DIRECTORY)
    if(EXISTS ${PARENT_DIR})
        message(STATUS "  Parent directory exists: ${PARENT_DIR}")
        file(GLOB PARENT_CONTENTS "${PARENT_DIR}/*")
        if(PARENT_CONTENTS)
            message(STATUS "  Parent directory contents:")
            foreach(ITEM IN LISTS PARENT_CONTENTS)
                get_filename_component(ITEM_NAME ${ITEM} NAME)
                if(IS_DIRECTORY ${ITEM})
                    message(STATUS "    [DIR]  ${ITEM_NAME}/")
                else()
                    file(SIZE ${ITEM} ITEM_SIZE)
                    message(STATUS "    [FILE] ${ITEM_NAME} (${ITEM_SIZE} bytes)")
                endif()
            endforeach()
        else()
            message(STATUS "  Parent directory is empty")
        endif()
    else()
        message(STATUS "  Parent directory does not exist: ${PARENT_DIR}")
    endif()
endif()