# Helper script to list directory contents for URG library build verification
# Usage: cmake -DDIR_TO_LIST=<directory> -P cmake/list_directory.cmake

if(NOT DEFINED DIR_TO_LIST)
    message(FATAL_ERROR "DIR_TO_LIST must be defined")
endif()

if(EXISTS ${DIR_TO_LIST})
    if(IS_DIRECTORY ${DIR_TO_LIST})
        file(GLOB DIR_CONTENTS "${DIR_TO_LIST}/*")
        if(DIR_CONTENTS)
            message(STATUS "Contents of ${DIR_TO_LIST}:")
            foreach(ITEM IN LISTS DIR_CONTENTS)
                get_filename_component(ITEM_NAME ${ITEM} NAME)
                if(IS_DIRECTORY ${ITEM})
                    message(STATUS "  [DIR]  ${ITEM_NAME}/")
                else()
                    file(SIZE ${ITEM} FILE_SIZE)
                    message(STATUS "  [FILE] ${ITEM_NAME} (${FILE_SIZE} bytes)")
                endif()
            endforeach()
        else()
            message(STATUS "Directory ${DIR_TO_LIST} is empty")
        endif()
    else()
        message(STATUS "${DIR_TO_LIST} exists but is not a directory")
    endif()
else()
    message(STATUS "Directory ${DIR_TO_LIST} does not exist")
endif()